name: publish

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup .Net
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Get current release version
        id: version
        run: echo "release=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT  

      - name: Build library and generate NuGet Package
        run: dotnet pack -c Release -o artifacts -p:PackageVersion=${{ steps.version.outputs.release }}
        working-directory: src/InvertedIndex.Infrastructure

      - name: Publish NuGet Package
        run: dotnet nuget push ./**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        
